apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Gi
  hostPath:
    path: /volume-data/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: default
spec:
  volumeName: minio-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi