apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minio.noise
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: console
            port:
              number: 10000