apiVersion: batch/v1
kind: Job
metadata:
  name: create-services-buckets
  namespace: minio
spec:
  template:
    spec:
      containers:
      - name: create-services-buckets
        image: minio/mc
        command:
          - sh
          - -c
          - |
            until mc alias set minio http://minio:9000 minio minio123 &&
              (mc ls minio/mlflow || mc mb minio/mlflow) &&
              (mc ls minio/postgres-backup || mc mb minio/postgres-backup);
            do
              echo waiting for minio;
              sleep 2;
            done;
      restartPolicy: OnFailure