source .cluster.local.env

export CLUSTER_CONFIG_LOCAL_PATH="$(pwd)/kind-cluster.yaml"
if ! [ -f "$CLUSTER_CONFIG_LOCAL_PATH" ]; then
    echo "$CLUSTER_CONFIG_LOCAL_PATH does not exist."
fi
export CLUSTER_CONFIG_REMOTE_PATH="$CLUSTER_CONFIG_PATH/kind-cluster.yaml"
UPLOAD_CLUSTER_CONFIG_CMD="sshpass -p $SSH_PASSWORD scp $CLUSTER_CONFIG_LOCAL_PATH $SERVER_USER@$SERVER_HOST:$CLUSTER_CONFIG_REMOTE_PATH"
echo $UPLOAD_CLUSTER_CONFIG_CMD
exit 0 
# eval $UPLOAD_CLUSTER_CONFIG_CMD