echo "Uploading cluster config to $SERVER_HOST"

export CLUSTER_CONFIG_LOCAL_PATH="../kind-cluster.yaml"
UPLOAD_CLUSTER_CONFIG_CMD="sshpass -p $SSH_PASSWORD scp $CLUSTER_CONFIG_LOCAL_PATH $SERVER_USER@$SERVER_HOST:$CLUSTER_CONFIG_HOST_PATH"
eval $UPLOAD_CLUSTER_CONFIG_CMD