apiVersion: v1
kind: Secret
metadata:
  name: cluster-superuser
  namespace: db
type: kubernetes.io/basic-auth
data:
  password: $POSTGRES_ROOT_PASSWORD_BASE64 
  username: $POSTGRES_ROOT_USER_BASE64