apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
  namespace: prefect
spec:
  volumeName: common-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
