apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-pv
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Gi
  hostPath:
    path: /volume-data