---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Gi
  hostPath:
    path: /volume-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
spec:
  volumeName: common-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
